# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18fOQwEl3uZ_LO_IKKUoNzthQ8hhrxf1g
"""

print("Hello new gcp")

#This is new

#This is main

